SupifyApp/Models/Friends.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupifyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}

SupifyApp/ViewModels/FriendsViewModel.cs
using SupifyApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SupifyApp.ViewModels
{
    public class FriendsViewModel
    {
        public FriendsViewModel()
        {
            Users u = new Users();

            List<Users> friendList = new List<Users>();
        }

        public Users u { get; set; }

        public IEnumerable<Users> friendList { get; set; }

    }
}

SupifyApp/ViewModels/HomePageViewModel.cs
using SupifyApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SupifyApp.ViewModels
{
    public class HomePageViewModel
    {
        public HomePageViewModel()
        {
            Users user = new Users();
            List<Playlist> Playists = new List<Playlist>();
            List<MusicConnections> ConnectionsList = new List<MusicConnections>();
        }

        public Users user { get; set; }

        public List<Playlist> Playists { get; set; }

        public List<MusicConnections> ConnectionsList { get; set; }
    }
}

SupifyApp/ViewModels/MusicViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SupifyApp.Models;

namespace SupifyApp.ViewModels
{
    public class MusicViewModel
    {
        public MusicViewModel()
        {
            List<Track> tracklist = new List<Track>();
            Users u = new Users();
        }

        public List<Track> tracklist { get; set; }

        public Users u { get; set; }
    }
}

SupifyApp/Controllers/PlayerController.cs
using SupifyApp.Models;
using SupifyApp.ViewModelBuilders;
using SupifyApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using JamendoApi;

namespace SupifyApp.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        public JamendoApiClient j = new JamendoApiClient("382429ae"); //no new write method needed iguess ?
        public SupinfydbEntities db = new SupinfydbEntities();

        FriendsModelBuilder fbuilder;
        // GET: Player
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomePage(HomePageViewModel h)
        {
            // tro marrant le projet
            return View(h);
        }

        public ActionResult Friends()
        {
            // pour récup le mec logged dans la session
            Users usr = getSessionUser();

            fbuilder = new FriendsModelBuilder();

            return View(fbuilder.Build(usr));
        }

        public ActionResult Music()
        {
            Users usr = getSessionUser();
            MusicModelBuilder mmb = new MusicModelBuilder();

            return View(mmb.Build(usr));
        }

        public class jsonMusicId
        {
            public int id { get; set; }
        }

        [HttpPost]
        public void Addtrack(jsonMusicId jid)
        {
            IEnumerable<Track> list = db.Track.OrderByDescending(p => p.Id);
            Track last = list.FirstOrDefault();

            Users usr = getSessionUser();
            Track m = new Track();
            m.trackid = jid.id.ToString();
            m.userid = usr.Id;
            if (last != null)
            {
                m.Id = last.Id + 1;
            }
            m.times_lstened = 0;
            m.added_date = DateTime.Now;

            if (db.Track.Where(p=>p.trackid == jid.id.ToString()).Count() == 0)
            {
                db.Track.Add(m);
                db.SaveChanges();
            }
        
        }

        public ActionResult AddPlaylist()
        {
            //TODOOOOOOOOOOOOOOOOOO
            return View();
        }

        public ActionResult AddFriends()
        {
            Users usr = getSessionUser();

            fbuilder = new FriendsModelBuilder();
            FriendsViewModel fvm = fbuilder.Build(usr);
            List<Users> usrList = db.Users.ToList();
            List<Users> friends = fvm.friendList.ToList();

            // magie noire ? STILL NOT FIXEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

            List<Users> canAdd = usrList.Except(friends).ToList();
            canAdd.Remove(usr);

            foreach (Users u in friends)
            {
                canAdd.Remove(u);
            }

            return View(canAdd);
        }

        //adds a friend
        public ActionResult Add(string id)
        {
            Users usr = getSessionUser();

            int friendId = int.Parse(id);

            IEnumerable<Friends> list = db.Friends.OrderByDescending(p => p.Id);
            Friends last = list.FirstOrDefault();

            Friends friend = new Friends();
            friend.FriendId = friendId;
            friend.UserId = usr.Id;
            if (last != null)
            {
               friend.Id = last.Id + 1;
            }

            db.Friends.Add(friend);
            db.SaveChanges();

            return RedirectToAction("AddFriends");
        }

        public ActionResult MyProfile()
        {

            Users usr = getSessionUser();

            UsersViewModel user = new UsersViewModel();
            user.Email = usr.Email;
            user.Firstname = usr.Firstname;
            user.Lastname = usr.Lastname;
            user.Password = usr.Password;
            user.Phone = usr.Phone;
            user.Username = usr.Username;

            return View(user);
        }

        public ActionResult ValidateEdit(UsersViewModel usr)
        {

            Users u = getSessionUser();
            int usrId = u.Id;

            var user = db.Users.Find(usrId);

            user.Email = usr.Email;
            user.Firstname = usr.Firstname;
            user.Lastname = usr.Lastname;
            user.Password = usr.Password;
            user.Phone = usr.Phone;
            user.Username = usr.Username;

            try
            {
                bool a = TryUpdateModel(user);
                //db.Entry(user).State = EntityState.Modified;    
                db.SaveChanges();

                return RedirectToAction("MyProfile");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("err", "Unable to save changes. Try again, and if the problem persists, call 911");
            }
                
            
            return RedirectToAction("MyProfile");
        }

        public Users getSessionUser()
        {

            string cookieId = FormsAuthentication.FormsCookieName;
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieId];
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);
            int usrId = int.Parse(ticket.Name);

            Users usr = db.Users.Where(u => u.Id == usrId).First();
            return usr;
        }


    }
}

SupifyApp/Views/Player/AddFriends.cshtml
@model IEnumerable<SupifyApp.Models.Users>

@{
    ViewBag.Title = "Add Friends";
}

<h2>Add Friends</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        <td>
            @Html.ActionLink("Details", "UserDetails", new { id = item.Id })
        </td>
        <td>
            @Html.ActionLink("Add", "Add", new { id = item.Id })
        </td>
    </tr>
}

</table>

SupifyApp/Views/Player/Friends.cshtml
@model SupifyApp.ViewModels.FriendsViewModel

@{
    ViewBag.Title = "Friends";
}

<h2><b>Manage friends</b></h2>
<br />

@if (Model.friendList.Count() == 0)
{
    ViewBag.rip = "You have no friends yet. Click the add button !";
}


<div class="col-lg-12">
    <div class="col-md-2">
        <input class="btn" type="button" value="Add Friends" onclick="location.href='@Url.Action("AddFriends", "Player")'" />
        <p></p>
    </div>

    <div class="col-md-10">
        <p style="color:dimgrey">@ViewBag.rip</p>
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Username")
        </th>
        <th>
            @Html.DisplayName("First Name")
        </th>
        <th>
            @Html.DisplayName("Last Name")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.friendList)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.ActionLink("Details", "UserDetails", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />

SupifyApp/Views/Player/HomePage.cshtml
@model SupifyApp.ViewModels.HomePageViewModel

@{
    ViewBag.Title = Model.user.Username;
}

<h2>Hello, @Model.user.Firstname @Model.user.Lastname</h2> 

<input type="button" value="Edit Profile" class="btn btn-lg btn_lgreen" onclick="location.href='@Url.Action("MyProfile", "Player")'" />
<input type="button" value="My Friends" class="btn btn-lg btn_lgreen" onclick="location.href='@Url.Action("Friends", "Player")'" />
<input type="button" value="My Music" class="btn btn-lg btn_lgreen" onclick="location.href='@Url.Action("Music", "Player")'" />
<br />
<br />
<br />
<div class="row">
    <input type="text" id="inputsearch" class="input-sm"/>
    <input class="btn" type="button" value="Search music" id="input" />   
</div>
<br />

<div id="search">
</div>

<div class="row">
    <div class="col-md-6">
        <h3>Recent Tracks</h3><input type="button" value="refresh" class="btn" onclick="location.reload()" />
        <div></div>
    </div>
    <div class="col-md-6">
        <h3 >Playlists</h3><input type="button" value="new playlist" class="btn" onclick="location.href='@Url.Action("AddPlaylist", "Player")'"/>
        <div></div>
    </div>
</div>

SupifyApp/Views/Player/Music.cshtml
@model SupifyApp.ViewModels.MusicViewModel

@{
    ViewBag.Title = "Music";
}

<h2>Music</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Track Name")
        </th>
        <th>
            @Html.DisplayName("Duration")
        </th>
        <th>
            
        </th>
        <th></th>
    </tr>
@{
    foreach (SupifyApp.Models.Track t in Model.tracklist)
    {
        <tr id="@t.trackid" class="mclass">
            
        </tr>
    }
}

</table>

SupifyApp/Views/Player/MyProfile.cshtml
@model SupifyApp.ViewModels.UsersViewModel

@{
    ViewBag.Title = "MyProfile";
}

<h2>My Profile - Edit</h2>

@using (Html.BeginForm("ValidateEdit","Player"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled"} })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ValidationMessage("err")
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SupifyApp/Views/Player/UserDetails.cshtml
@model SupifyApp.ViewModels.UsersViewModel

@{
    ViewBag.Title = Model.Username + "'s Profile";
}

<h2>ViewBag.Title</h2>

@using (Html.BeginForm("ValidateEdit","Player"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled"} })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ValidationMessage("err")
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}